### ISSUE TITLE
[Wiki]新手包

### ISSUE THREAD

**Issue by gzMichael** [JianyiFutures/intern#1]
# 欢迎你，团队的新人！

## 实习的目标

- 熟练使用Github、Markdown、印象笔记、M$ Office等常用工具
- 掌握如何获取国内、国外豆粕和玉米的产量、库存信息
- 掌握如何获取航运信息
- 初步掌握从`产地`到`市场`这一链条上各环节的信息收集及汇总
- 能进行简易的数据分析

## 实习时间安排

- 170320-170428 0wd1-5wd5 实习第一阶段
- 170502-170630 6wd2-14wd5 实习第二阶段

说明：无论最终是否在简一投资入职，我们都将为你发放实习期间的证明。

------

# 软件使用

## Github

- Github是托管开源代码的平台，我们目前使用Github进行项目的管理
- 关于Github的介绍，可以参考Github的 [Hello World](https://guides.github.com/activities/hello-world/) 文档。我们只使用了部分的功能，所以了解内容即可，如果需要托管项目代码，则需要熟悉全部的内容。

作业：
- 在[项目的页面](http://github.com/jianyifutures/intern)中到处看看，了解基本的使用。
- 查看Issues的内容，尝试回复或者发一个新Issue
- 将项目目录Fork到自己的repo，在自己的相应目录中写学习和工作总结

## Markdown

- 什么是Markdown？
- Markdown有什么作用？
- 这个新手包是用Markdown的格式写的吗？
- Github支持Markdown格式吗？
- 有哪些Markdown编辑器可以使用？
- 可以参考一下[Github与Markdown主题分享会](http://mp.weixin.qq.com/s/CHjtI2roiuNaQVCwz9WC1A)的内容

作业：用Markdown格式写一下你摸索Github和Markdown的经验

## 印象笔记

- 你有使用过印象笔记吗？它的作用是什么？
- 如何与同事们一起共享笔记内容？
- 如果你在微博、网页、微信上看到一篇好文章，你如何将它收集到印象笔记？
- 尝试过用标签、笔记本对笔记内容进行分类和整理吗？

作业：注册印象笔记账号，并加入到工作群聊中。

## PPT/EXCEL

- 手头有一些数据需要整理，能否通过Excel的函数、宏和小程序让自己更轻松地获得预期的结果呢？
- 论文要答辩了，能否做一个清爽的PPT，让评委们能迅速地了解我的论文思路呢？
- 是不是还漏了Word？请重新阅读一下上面的Markdown部分。

## 期货相关软件

- 行情软件：[文华财经](http://www.wenhua.com.cn/)、[招商证券](http://www.newone.com.cn/public/dwloadcenter/index.html)（通达信）
- 交易软件：[易盛](http://www.esunny.com.cn/index.php?m=content&c=index&a=lists&catid=22)、快期
- 行情软件查看实时行情，交易软件进行下单，部分软件两者均支持。

------

# 工作规范

## 时间点的书写

时间的缩写规则：w ~ week 周，d ~ day 日，每周以周日(*wd0)作为开始，以周六(d6)结束。以实习开始日所在的星期为起点，170320是0wd1，170331 是1wd5，以此类推。

## 快速迭代

- 我们期望让每个文档都成为一个产品，所以我们需要持续进行迭代更新；
- 如果你发现了文档的内容存在错误，请立即指出，我们会马上修正；
- 如果你觉得你能写出更好的文档内容，请不要犹豫，马上在Issue进行提交，我们会尽快更新到文档中；
- 如果你在工作中有更好的建议，欢迎新建Issue进行讨论！

## 随手记录，日积月累

当你做某件事有心得时，请记录并分享你的心得，让其他同伴可以共享到你的成果。在实习的过程中，安排了编写总结、教程的内容，让写作成为你的习惯吧。

## 沟通方式

- 在工作中如果频繁地使用QQ群、微信群等工具，一是信息过于碎片化，沟通后不能对沟通成果进行沉淀，二是可能会中断其他人的工作，所以我们推荐使用Github和邮件的方式进行**异步沟通**。
- 沟通的姿势：
  - 在Github新开Issue，其他同事将会在看到Issue提示后给予回复；
  - 如遇到紧急需沟通的事宜，请即通过微信或者电话沟通。

## 学习方法

- 站在源头，获取第一手资料

养成从源头获取第一手资料的习惯，然后通过自己的分析，形成自己的决策树。获取第一手资料，可以保证资料的时效性和正确性，让自己的决策基础更稳健。

- 用输出代替输入

最好的学习方法是尝试去“教”别人，在这个过程中，自己才能有更深刻的体会。所以最好的学习材料就是：你写给自己的教程。尝试去教半年前的自己，这些问题应该如何去学。单纯的看书是输入，未必能形成自己的知识体系，只有用输出倒逼输入，才能更好地进行学习。多写文章，多做分享，便是学习的捷径。

## 感受同侪压力，被动前进

如果你身旁的小伙伴很快解决了一个又一个的问题，你是否会感受到前进的压力呢？所以多和小伙伴们交流，互相讨论和学习，可以让大家更快地携手前进！

# 结语

看完上面，你是不是要开始去下载软件，马上进行尝试呢？

ChangeLog
---------------
2017.3.3 Michael创建

**Comment by XifenYE** [comment]
TEST

**Comment by XifenYE** [comment]
请问如何加入印象笔记工作群聊呢？需要输入什么邮箱地址？

![](https://github.com/XifenYE/-/blob/master/home/5.png?raw=true)

@gzMichael

**Comment by gzMichael** [comment]
> 请问如何加入印象笔记工作群聊呢？需要输入什么邮箱地址？

请你发一下你注册印象笔记的邮箱给我，我加你进工作群聊。

**Comment by gzMichael** [comment]
> 请问如何加入印象笔记工作群聊呢？需要输入什么邮箱地址？

@XifenYE 请你发一下你注册印象笔记的邮箱给我，我加你进工作群聊。

**Comment by XifenYE** [comment]
505553108@qq.com 谢谢^^
@gzMichael

**Comment by gzMichael** [comment]
已经邀请加入，请在印象笔记的工作群聊查看。

**Comment by superke7** [comment]
新人报道~

**Comment by gzMichael** [comment]
Issue关闭，放入Wiki。
https://github.com/JianyiFutures/intern/wiki/%E6%96%B0%E6%89%8B%E5%8C%85
