### ISSUE TITLE
如何到其他同学的仓库串门？

### ISSUE THREAD

**Issue by gzMichael** [JianyiFutures/intern#11]
# 论串门的姿势

@JianyiFutures/all  刚刚熙芬同学提交了最新的探索记录，我在这里就用这次提交作为例子，给大家展示一下如何到其他同学的仓库进行串门学习。

## 入口1：Dashboard
点击orgs/JianyiFutures的[Dashboard](https://github.com/orgs/Jianyifutures/dashboard)，可以看到仓库文件的变化，以及最新的Issue提交。

![](http://i.imgur.com/JD3eOOA.png)

在Dashboard就可以看到历次的更新记录了，还包括了Issues的所有操作（新建、回复、关闭等）。但如果其他同学只更新了自己的仓库，并没有在组织的Issue提交，在这里是看不到的。这时候需要使用入口2来跟踪学习。

## 入口2：进入同学的仓库

- 查看组织的[成员名单](https://github.com/orgs/JianyiFutures/people)，点击每个同学的链接，然后进入他/她的intern，就可以看到类似下面的信息：

![](http://i.imgur.com/FyKQuq8.png)

- 找到最近更新的目录或者文件，然后进入查看。我们可以看到最近更新的就是USDA_Reports目录，进入后，右边有"History"按钮，点击就能查看到所有的更新记录了。

![](http://i.imgur.com/9aiwEOJ.png)

------

![](http://i.imgur.com/VVvjAoQ.png)

- 点击该次更新序号，能查看到具体的文件变更内容（其中绿色的为新增部分，红色为删减部分。如果在段中插入文字的，将体现为删除原来段落、插入新段落以及原来在插入点后的文字）：

![](http://i.imgur.com/mTSjn3R.png)

- 可以选择在具体某一行或文末，插入你的评论和回复。

### 学会以上的步骤后，记得多到其他同学那里串门学习哦。

**Comment by gzMichael** [comment]
@JianyiFutures/all 据说很多同学都没有收到新Issue的推送，确实是这样吗？
期待大家回复一下

**Comment by PwenWung** [comment]
我是。我是用163不行的，前面的新issue没收到




发自网易邮箱大师
在2017年03月23日 00:29，gzMichael 写道：

@JianyiFutures/all 据说很多同学都没有收到新Issue的推送，确实是这样吗？
期待大家回复一下

**Comment by 65Xiaomeng65** [comment]
收到啦！^_^

gzMichael <notifications@github.com>于2017年3月22日 周三12:30写道：

**Comment by XifenYE** [comment]
大部分都能收到的~

**Comment by gzMichael** [comment]
放入Wiki，Issue关闭。
https://github.com/JianyiFutures/intern/wiki/%E5%A6%82%E4%BD%95%E5%88%B0%E5%85%B6%E4%BB%96%E5%90%8C%E5%AD%A6%E7%9A%84%E4%BB%93%E5%BA%93%E4%B8%B2%E9%97%A8%EF%BC%9F
