### ISSUE TITLE
[2wd4(170406)] 大豆和豆粕市场价格分析因素 课程通知

### ISSUE THREAD

**Issue by gzMichael** [JianyiFutures/intern#15]
@JianyiFutures/all  本周四（后天）将进行第三次课程，通知如下：

## 上课时间

2wd4 (170406，周四) 15:00 

## 上课地点
在[环球都会广场](http://j.map.baidu.com/zrDrB)的2008-2009单元，具体位置是珠江新城花城大道和冼村路路口的西南方。

![](http://i.imgur.com/1jJI41g.png)

联系人：陈宁 13316097708

## 课程内容
在上次课程基础上，继续讲解大豆、豆粕市场价格分析因素

## 课前准备
查看 #10 中的全部内容
上次课程内容

## 注意事项
- 由于大厦需要在前台登记才能进入，请大家于14:50在一楼大堂集合，然后再一起上去。
- 请在收到本通知后在下面回复，如不能参加课程的也请在此提出请假。

**Comment by PwenWung** [comment]
收到，准时出席




发自网易邮箱大师
在2017年04月04日 21:27，gzMichael 写道：

@JianyiFutures/all 本周四（后天）将进行第三次课程，通知如下：

上课时间

2wd4 (170406，周四) 15:00

上课地点

在环球都会广场的2008-2009单元，具体位置是珠江新城花城大道和冼村路路口的西南方。

联系人：陈宁 13316097708

课程内容

在上次课程基础上，继续讲解大豆、豆粕市场价格分析因素

课前准备

查看 #10 中的全部内容
上次课程内容

注意事项
由于大厦需要在前台登记才能进入，请大家于14:50在一楼大堂集合，然后再一起上去。
请在收到本通知后在下面回复，如不能参加课程的也请在此提出请假。

**Comment by XifenYE** [comment]
收到，需要请假，非常抱歉。

**Comment by GM163** [comment]
收到，会准时到的。

**Comment by superke7** [comment]
收到,准时参加

**Comment by gzMichael** [comment]
@JianyiFutures/all 课程更改到明天(170410) 15:00 进行，地点不变，请大家准时参加。

**Comment by PwenWung** [comment]
收到




发自网易邮箱大师
在2017年04月09日 21:49，gzMichael 写道：

@JianyiFutures/all 课程更改到明天(170410) 15:00 进行，地点不变，请大家准时参加。

**Comment by GM163** [comment]
好的，收到




发自网易邮箱大师
在2017年04月09日 21:50，王沛文 写道：
收到




发自网易邮箱大师
在2017年04月09日 21:49，gzMichael 写道：

@JianyiFutures/all 课程更改到明天(170410) 15:00 进行，地点不变，请大家准时参加。

**Comment by superke7** [comment]
收到,准时参加

**Comment by XifenYE** [comment]
收到~

**Comment by gzMichael** [comment]
课程结束，作业另开Issue提交。
