### ISSUE TITLE
同学们，不要放过问问题的机会啊！

### ISSUE THREAD

**Issue by gzMichael** [JianyiFutures/intern#18]
@JianyiFutures/all 今天大家在办公室也讨论了好几个问题，这非常好。有的问题解决了，但还有的可能没有解决，怎么办？感觉发Issue提问啊！

比如 @PwenWung 的压榨利润计算问题， @GM163 的产量预估数据获取问题，等等。。

提问之前，可以参考一下下面的Issues：
- #12 如何用 Issue 提个好问题
- #11 如何到其他同学的仓库串门？
-  #8 如何查看已关闭的Issue？

**最重要的是**千万不要放过你的疑问，千万不要觉得不好意思。每次提问都是你的探索过程！

**Comment by gzMichael** [comment]
#16 @qinzhengyu 同学发了一个问题，但马上就close了，不知道解决了没有。

**Comment by superke7** [comment]
我看没人问,还以为发错地方了,那个压榨利润计算问题是我问的啊![Markdown](http://i1.piimg.com/1949/c3ae9b69eb320f61.png)  
能不能把issues的标签功能权限开放啊? @gzMichael

**Comment by gzMichael** [comment]
> 我看没人问,还以为发错地方了,那个压榨利润计算问题是我问的啊![](https://camo.githubusercontent.com/380e80ff439d9d603998ca0cc066e3b88d9dfafd/687474703a2f2f69312e7069696d672e636f6d2f313934392f633361653962363965623332306636312e706e67)

@qinzhengyu 在这里尽管提问即可，压榨利润的计算问题请开Issue提问。

> 能不能把issues的标签功能权限开放啊? @gzMichael

这个不用担心，我会把大家打上相应的标签。

**Comment by superke7** [comment]
OK~
