### ISSUE TITLE
72h[TASK] 整理美国农业部报告链接

### ISSUE THREAD

**Issue by gzMichael** [JianyiFutures/intern#19]
### USDA agency reports:

- WASDE (World Agricultural Supply and Demand Estimates，每月10号附近更新)

http://usda.mannlib.cornell.edu/MannUsda/viewDocumentInfo.do?documentID=1194

- Crop Progress(4~11月每周更新)

http://usda.mannlib.cornell.edu/MannUsda/viewDocumentInfo.do?documentID=1048

- Grain Stocks(每年1/3/6/9月更新)

http://usda.mannlib.cornell.edu/MannUsda/viewDocumentInfo.do?documentID=1079

- Prospective Plantings(每年3月底更新)

http://usda.mannlib.cornell.edu/MannUsda/viewDocumentInfo.do?documentID=1136

### 按日历查看报告：

https://www.nass.usda.gov/Publications/Reports_By_Date/index.php

https://www.ers.usda.gov/calendar/

![2017-04-11_171852](https://cloud.githubusercontent.com/assets/23654385/24901877/fd06b906-1eda-11e7-861d-42986a968d4d.png)

**Comment by gzMichael** [comment]
超时关闭，合并至Wiki。

**Comment by gzMichael** [comment]
### 增补
在 Wiki 中，加入 `Foreign Agricultural Service` 查询地址，可以查询中国等外国的数据。
https://apps.fas.usda.gov/psdonline/app/index.html#/app/advQuery

- Wiki 链接
https://github.com/JianyiFutures/intern/wiki/USDALink1

**Comment by gzMichael** [comment]
感觉需要继续增补，重开 Issue。

**Comment by gzMichael** [comment]
这个给 @XifenYE 更新。

**Comment by XifenYE** [comment]
补充：
- [《月度美国大豆压榨报告》](https://usda.mannlib.cornell.edu/MannUsda/viewDocumentInfo.do?documentID=1902)
- [《出口销售报告》](https://apps.fas.usda.gov/export-sales/esrd1.html)
- 出口销售数据检索：
https://apps.fas.usda.gov/esrquery/esrq.aspx
- 农作物播种进度&生长情况数据检索：
https://apps.fas.usda.gov/export-sales/esrd1.html

**Comment by XifenYE** [comment]
注：每周出口销售报告的数据常常不够准确，因为很常在下一周会对上一周数据进行更正，也就是说上一周报告中的数据是错的，比如3.30号报告中国销售量是37.01，但是4.6号报告就有对中国数据的Adjustments，3.30号数据应该是37.01-6.44=30.57，同时总的出口销量也有变化
![Markdown](http://i1.piimg.com/591986/00d4191e8cfd8b7e.jpg)
- 因此推荐使用检索系统导出的数据，都是更正过的，比较准确
![Markdown](http://i1.piimg.com/591986/260a58967793c1de.png)

**Comment by PwenWung** [comment]
用熙芬提供的出口销售数据检索网站，下载excel格式的数据表，用筛选功能对表头进行处理，然后选择Grand total 或者china 可以得到只与目标有关的excel格式数据，在做历史数据表格时，采用这样的方法进行处理比较快捷。

**Comment by gzMichael** [comment]
@PwenWung 放个excel文件，看看公式啊，或者截个图也行

**Comment by PwenWung** [comment]
![Markdown](http://i2.muimg.com/590848/464787eef618c7e8.png)
1. 如图，要下载excel格式的历史数据表，然后按图一对表头进行筛选功能处理
![Markdown](http://i2.muimg.com/590848/883f8221abdce750.png)
2. 在country 项输入Grand total ，确定
![Markdown](http://i2.muimg.com/590848/d38ad71852a85456.png)
3. 蹬蹬蹬蹬，经过处理后，会得到如图三所示，可以直接整列复制黏贴的，我们直接可以采用的目标数据，注意有个一个是ending MY，有一个是starting MY~

**Comment by XifenYE** [comment]
更新完毕，issue关闭~
