### ISSUE TITLE
新手作业提交处

### ISSUE THREAD

**Issue by gzMichael** [JianyiFutures/intern#2]
## 学习安排

学习任务已经在 [新手包](https://github.com/JianyiFutures/intern/issues/1) 中安排，请自行前往查看并领取任务。主要有以下两点：

- 注册Github，并加入项目。
- 注册印象笔记，并加入工作群聊。这样才能获取到工作所需要的资料。
- 有时间的还可以注册和登录期货的模拟交易账户，尝试做几笔期货交易。

以上都完成的话，相信你一定有新的体会和感受，那就赶紧在自己的目录下，把心得体会记录下来。

## 作业提交方法：

请你回复本 Issue ，提交你的学习和工作心得，或者在此提出疑问，无论是分享心得或者提出疑问，都请加上一些简要说明或者截图，方便其他人查看或者协助。有需要的话也可以显式艾特其他人，比如 @gzMichael 。

模板如下：

    - 任务完成情况：......
    - 任务成果截图：……
    - 个人教程地址： ……  （如有请一定要附上）
    - 感想： ...... 140 字以上，你的心得、疑问均可。

期待在这里看见你的回复！

**Comment by gzMichael** [comment]
@PwenWung 同学在 #6 的回复，可以在这里提交：
[我的仓库链接](https://github.com/PwenWung/intern)

**Comment by XifenYE** [comment]
心得汇总：
[Gibhub初体验](https://github.com/XifenYE/intern/blob/master/Tools/Notes/Github%E5%88%9D%E4%BD%93%E9%AA%8C.md)
[关于Markdown](https://github.com/XifenYE/intern/blob/master/Tools/Notes/%E5%85%B3%E4%BA%8EMarkdown.md)
[我眼中的期货](https://github.com/XifenYE/intern/blob/master/Foundation/note/%E6%88%91%E7%9C%BC%E4%B8%AD%E7%9A%84%E6%9C%9F%E8%B4%A7.md)
[3.17交易心得](https://github.com/XifenYE/intern/blob/master/Trading/note/3.17%E4%BA%A4%E6%98%93%E5%BF%83%E5%BE%97.md)

**Comment by gzMichael** [comment]
直接把文件或者文章所在目录发出，可能更好：
笔记文件：[我的仓库链接](https://github.com/XifenYE/intern/blob/master/Trading/note/3.17%E4%BA%A4%E6%98%93%E5%BF%83%E5%BE%97.md)

**Comment by GM163** [comment]
[初步了解期货](https://github.com/GM163/intern/blob/master/Foundation/note/%E5%88%9D%E6%AD%A5%E4%BA%86%E8%A7%A3%E6%9C%9F%E8%B4%A7.md)

[对GitHub、Markdown、Evernote的初步认知](https://github.com/GM163/intern/blob/master/Tools/note/%E5%AF%B9GitHub%E3%80%81Markdown%E3%80%81Evernote%E7%9A%84%E5%88%9D%E6%AD%A5%E8%AE%A4%E7%9F%A5.md)

**Comment by 65Xiaomeng65** [comment]
关于Markdown与Github的感想：[我的仓库链接](https://github.com/65Xiaomeng65/intern)

**Comment by 65Xiaomeng65** [comment]
期货初探：[我的仓库链接](https://github.com/65Xiaomeng65/intern)

**Comment by gzMichael** [comment]
大家都提交了作业，本Issue关闭。
