### ISSUE TITLE
"豆粕指数"和"豆粕主连"代表什么?

### ISSUE THREAD

**Issue by superke7** [JianyiFutures/intern#20]
@JianyiFutures/all
## 现象和背景  
打开交易软件发现每种交易品种除了每月的合约以外,还有指数和主连
![Markdown](http://i1.piimg.com/1949/8e927c943d69307e.png)  
## 尝试:  
 交易下发现可以进行买进卖出  
## 推测:
与普通期货合约一样,可进行交易,具体定价方式还在探索中  
## 解释链接  
 - [链接1](http://blog.sina.com.cn/s/blog_4c6084460102wkvr.html)  [链接2](http://blog.sina.com.cn/s/blog_525b8ce90102w057.html)   [链接3](https://www.zhihu.com/question/53010999)

**Comment by gzMichael** [comment]
每个品种都会有主连和指数，区别是：
- 主连合约就是把主力合约“拼”起来的合约，看主连合约就不需要关心目前哪个是主力合约，直接看即可。但切换合约时，两个合约价格不一样，会出现跳空的现象。

- 指数就是几个合约的加权，算法是：主力合约占主要权重，远期合约次之。比如在通达信的豆粕指数算法可能是：主力合约（09）75%，01合约20%，05合约5%。这个算法每个行情软件都不一样，仅供参考用。

- 在部分的软件中，主连可能可以交易，这个映射到实际合约即可，但指数是不能买卖的，最多只能作回测用途。

### 提问非常值得鼓励，同时也要思考以下问题：
- 这个问题是否能通过在网络搜索解决？如果不能解决，是否搜索的关键词，或者搜索的网站不对？
- 我自己的思考是怎样的？比如指数会不会就是。。。，然后我再核实一下我的答案？

### 补充
- 提问Issue的开头，请 @JianyiFutures/all 全部人，以便其他人能收到你的问题Issue推送
- 写出自己的探索过程，越详尽越好。甚至可能你在写的过程中，就把这个问题解决了。

**Comment by superke7** [comment]
@JianyiFutures/all 问题已解决,参考答案在上方
