### ISSUE TITLE
压榨套利计算表数据来源

### ISSUE THREAD

**Issue by XifenYE** [JianyiFutures/intern#21]
-  压榨套利大豆到港成本=（CBOT期货价+升贴水）×0.367433 ×汇率×（1+3%）×（1+13%）+100 
    压榨利润=豆粕期价×0.79+豆油期价×0.19-大豆进口成本-120

- 其中计算南美进口大豆利润时，CBOT期货价为7月SN，贴水为7月船期贴水，汇率为6个月远期汇率，豆粕期价为M1709，豆油期价为Y1709，为什么？
1. 个人理解：进口南美大豆，对应CBOT大豆7月合约，对应7月南美船期贴水，大豆加工后出厂销售对应DCE豆粕、豆油9月合约，由此计算压榨利润，那么为什么使用6个月远期汇率呢？
2.  第二种思考：压榨套利就是基于CBOT大豆价格与DCE豆粕、豆油价格之间的密切关系，他们的价差（即榨利）存在一个合理区间，经验来看是CBOT 大豆7月合约与DCE 豆粕/豆油9月合约具有这种比价关系，又由于是计算未来利润，那么需要使用远期汇率。

**Comment by gzMichael** [comment]
记得 @JianyiFutures/all 哦，不然其他同学可能收不到。

**Comment by gzMichael** [comment]
合并至 #26 一起讨论，本 Issue 关闭。
讨论完成后，一起收纳入Wiki。
