### ISSUE TITLE
[ASK] 你还在用Github的文本框进行输入吗？

### ISSUE THREAD

**Issue by gzMichael** [JianyiFutures/intern#22]
@JianyiFutures/all 大家在用Github的时候，是直接在文本框里面编辑吗？
### 痛点
- 浏览器非法操作
- 输入响应时间慢，插入图片经常超时
- 无法实时预览，“Preview”按钮的体验，相信大家都懂的。。
- 不小心按了后退，回来之后内容全没了
以上各种情形，如果出现在你辛辛苦苦输入后，发现内容丢失时，你是否会感到崩溃？

### 需求
有痛点就有需求，对应地，我们想找到：
- 浏览器崩溃也能继续编辑
- 本地化编辑，省去网络的时延
- 可以预览

### 好物
Firefox浏览器的It's All Text!插件，可以绑定本地文本编辑器。
在文本框旁边点一个小按钮，马上就会将内容跳转到文本编辑器进行编辑，是不是很方便？
![](http://olg46z18j.bkt.clouddn.com/itsalltext.png)
要用这个插件，就必须使用Firefox浏览器。

### 思考
- 本地用什么编辑器好？MarkdownPad？
- 为什么好？
- 有没有更好的？

**Comment by superke7** [comment]
## 本地编辑 :
- 小书匠 or Atom  +图片上传
## 小书匠 :  
优点：功能丰富，界面美观，大部分代码可图形化界面操作，但实际还是代码方便  
缺点：软件打开速度慢，与github兼容微微不好，如“==123==”在小书匠里为引用，而在github里没有该代码
![Markdown](http://i4.buimg.com/1949/7415b55a807c55fa.png)  
## Atom：  
优点：稳定，与github兼容较好，插件非常丰富
缺点：文档标签比较乱，最大的缺点是不能默认显示预览，每次要ctrl+Shift+M，查看md文件不方便（可能是还我没找到）  
![Markdown](http://i1.piimg.com/1949/3857c9e8d0af8b0d.png)  
## 图片上传：[贴图库](http://www.tietuku.com/upload)  
- 优点: 一个网站而已,无需安装,简单快速,截图后可直接粘贴,且可直接生成MARKDOWN链接,非常方便  
- 缺点:有可能在后期图片链接会挂掉,毕竟是第三方图片存储  
![image](https://cloud.githubusercontent.com/assets/26921913/25039880/aabec322-2138-11e7-89e6-0b88a7b57b85.png)

希望有chrome的插件~

**Comment by XifenYE** [comment]
## 个人使用习惯:cmd作业部落+七牛云
### 优点
- 界面美观，字体疏密得当。
![](http://oo8xbd69m.bkt.clouddn.com/%E7%81%AB%E7%8B%90%E6%88%AA%E5%9B%BE_2017-04-14T07-19-01.807Z.png)
- 格式与Github兼容，复制全文粘贴到github中预览与当前一致。（Markdownpad会出现粘贴或上传到github后不兼容，成品与当时编辑器中预览不一致的情况）
- 实时更新，实时自动在线云保存，不用担心文档遗失。
- 上传本地图片需要付费，听取Michael的建议后开始搭配七牛云使用，获取图片外链非常方便，不会出现github经常超时的问题。
![](http://oo8xbd69m.bkt.clouddn.com/%E7%81%AB%E7%8B%90%E6%88%AA%E5%9B%BE_2017-04-14T07-24-16.611Z.png)
<br/>

![](http://oo8xbd69m.bkt.clouddn.com/%E7%81%AB%E7%8B%90%E6%88%AA%E5%9B%BE_2017-04-14T07-24-20.403Z.png)

- 会积极尝试大家提供的不同的编辑器和编辑经验，慢慢探索出最适合自己，同时最高效的编辑方法~

**Comment by gzMichael** [comment]
@qinzhengyu 这是讨论帖，也请详尽回复一下啊。
比如你对Atom探索是怎样的？它可以用来做什么？

**Comment by superke7** [comment]
已补完~ @gzMichael

**Comment by gzMichael** [comment]
@qinzhengyu Atom支持Markdown Preview可是不错的哦，还有qiniu插件可以上传图片，有探索过吗？

**Comment by gzMichael** [comment]
@JianyiFutures/all 其他同学在Issue发布42小时内请回复，过期将关闭。

**Comment by superke7** [comment]
这么多功能啊,我研究研究~@gzMichael

**Comment by PwenWung** [comment]
[作业部落](https://www.zybuluo.com/)搭配[贴图库](http://www.tietuku.com)

- 作业部落美观，实时浏览格式，流畅，云端保存历史。

- 贴图库登陆账号后可以批量上传，而且一键复制markdown格式的图片链接。

- 但用作业部落写完后转移到github上时常有问题：


1. 若采用导出后上传的方法，github时不时就上传失败

2. 若采用直接复制黏贴，github上时不时就丢掉格式效果和设置不了自动换行

**Comment by gzMichael** [comment]
以上所有的问题都归结到一个点：如何最快捷可以达到我们的目的？

Issue已到时关闭，大家可以继续思考，也可以在后面继续回复。
