### ISSUE TITLE
[4wd1(170417)] 大豆和豆粕市场价格分析因素 课程通知

### ISSUE THREAD

**Issue by gzMichael** [JianyiFutures/intern#23]
@JianyiFutures/all 今天（周一）下午将进行第四次课程。

## 上课时间

4wd1 (170417，周一) 15:00 

## 上课地点
在[环球都会广场](http://j.map.baidu.com/zrDrB)的2008-2009单元，具体位置是珠江新城花城大道和冼村路路口的西南方。

![](http://i.imgur.com/1jJI41g.png)

联系人：陈宁 13316097708

## 课程内容
本次课程继续讲解豆粕市场价格分析因素

**Comment by gzMichael** [comment]
@JianyiFutures/all 刚刚接罗总通知，课程需要改在明天下午进行，请大家知照。

**Comment by GM163** [comment]
收到 明天准时到




发自网易邮箱大师
在2017年04月17日 12:53，gzMichael 写道：

@JianyiFutures/all 刚刚接罗总通知，课程需要改在明天下午进行，请大家知照。

**Comment by PwenWung** [comment]
收到了
在2017年04月17日 12:53，gzMichael 写道：

@JianyiFutures/all 刚刚接罗总通知，课程需要改在明天下午进行，请大家知照。

**Comment by gzMichael** [comment]
@JianyiFutures/all  课程时间改为 4wd5(170421，周五) 15:00，请大家知照。

**Comment by gzMichael** [comment]
课程结束，作业布置在 Issue #27 ，本 Issue 关闭。
