### ISSUE TITLE
72h[ASK] 汇率和贴水如何影响压榨套利？

### ISSUE THREAD

**Issue by XifenYE** [JianyiFutures/intern#26]
- 理解误区：随汇率和贴水的变动方向进行套利操作。
- 纠偏：做套利的时候汇率和贴水是风险因素，要纳入考虑范围。压榨利润计算包括了升贴水波动，是汇率变化的全价值链利润，汇率和贴水对于套利投机者而言是敞口头寸。在做期货盘面压榨套利策略时，承担这些升贴水和汇率等变量带来的风险，可能带来额外收益，也可能加重损失。不知道这样理解对不对？

- 个人思考：
1. 汇率：
据4.12日收盘价计算新季美国大豆压榨利润如下：
![](http://oo8xbd69m.bkt.clouddn.com/412%E6%A6%A8%E5%88%A9.png)
如果此时判断压榨利润偏低，超过理论范围，进行反向套利，买入DCE豆粕、豆油，卖出CBOT大豆。
持单到4.17日收盘，压榨利润已显著回升，套利操作有收益：
![](http://oo8xbd69m.bkt.clouddn.com/417%E6%A6%A8%E5%88%A9.png)
观察可见此时贴水不变，汇率有所上升，假定4月17日远期汇率从4月12日的6.9872进一步上升到7.2，发现压榨利润会进一步降低，套利操作亏损：
![](http://oo8xbd69m.bkt.clouddn.com/%E5%81%87%E5%AE%9A%E6%B1%87%E7%8E%87.png)
- 因此，远期汇率上升（美元升值，人民币贬值）对于套利交易的影响体现在：做反向套利时，压榨利润会进一步缩减，造成损失；做正向套利时则相反，加速了压榨利润回落到正常区间，增加收益。汇率下跌的理解以此类推。
- 体现在决策上，就是套利前，要对远期汇率做一个预测。打个比方，如果做反向套利时判断远期汇率上升，人民币将贬值，则获利空间有限，保持谨慎，不轻易入场。
2.  升贴水
- 思路与理解汇率类似，升贴水上升：利空榨利，做反向套利时，压榨利润会进一步缩减，造成损失；做正向套利则加速压榨利润回落到正常区间，增加收益。
3. 理解可能有偏颇，希望可以看到其他小伙伴的思考~~
@JianyiFutures/all

**Comment by gzMichael** [comment]
很不错的思考，过程很详细~
能加入几个参考链接就完美了。

**Comment by GM163** [comment]
- 之前的思考方向：
汇率、升贴水     压榨套利

- 重新理解方向：
压榨套利        汇率、升贴水对其影响方向     是否做压榨套利、怎样做


- 假设原本的压榨套利是-150，汇率/贴水上涨，变为-200，如若汇率不上升，压榨利润回归，则盈利；但是由于汇率上升，在相同时间内平仓是亏的。

- 问题1：为什么不加长时间等到回到正常值时再平仓？及时平仓是风控的一部分？

- 问题2：汇率和贴水反向变动的情况下，应该怎么做？

- 问题3：汇率/贴水影响CBOT和DEC，CBOT和DEC又相互关联，所有的关联数值都成为变量，这时候应该如何判断？

**Comment by PwenWung** [comment]
[汇率贴水正反套](https://github.com/PwenWung/intern/blob/master/Trading/%E5%8E%8B%E6%A6%A8%E5%88%A9%E6%B6%A6%E4%B8%8E%E6%AD%A3%E5%8F%8D%E5%A5%97.md)我觉得可以直接把看涨看跌汇率，贴水当成影响到底做正套还是反套的主要因素，正反套就是对压榨利润缩小放大的操作，而合理区间不是作为决定正反套操作的因素。

**Comment by gzMichael** [comment]
@GM163 

> 问题1：为什么不加长时间等到回到正常值时再平仓？及时平仓是风控的一部分？

套利前是否可以区分 `正常值` 和 `不正常值` ？
开仓前的操作策略是怎样的，比如止盈止损位置？

> 问题2：汇率和贴水反向变动的情况下，应该怎么做？

这个问题是指汇率上升、贴水下降的情形吗？
需要有实际例子/数据描述一下。

> 问题3：汇率/贴水影响CBOT和DEC，CBOT和DEC又相互关联，所有的关联数值都成为变量，这时候应该如何判断？

我的个人看法，欢迎上课讨论：
- 找出哪个是因，哪个是果
- 哪个因素近期变化最大，并找出其原因

**Comment by gzMichael** [comment]
@PwenWung 需要将问题再描述得具体一点，才好给你回应。

可以参考Wiki链接：
https://github.com/JianyiFutures/intern/wiki/How2Ask_ZH

**Comment by PwenWung** [comment]
目前有几种理解，不知道哪种正确，个人偏向于1，另外还有汇率的部分疑问
![Markdown](http://i4.buimg.com/590848/ecfd68e25c3aa73b.jpg)
图一A点，压榨利润超过了预期的正常区间（理应正套），有一段上涨后继续回落正常区间。图二是榨利图，图三是汇率，汇率看跌（理应反套）。
1、图一的区间是主要的决定因素，决定图二趋势，汇率等因素变化是次要（因为汇率相对于CBOT与DEC的相对变化来说很慢，波动很小），所以仅作为影响因素处理
2、图一图三依然是并列重要的因素，当二者理应的操作方向相同，获利较为确定，否则，要考虑二者的影响程度再决定正反套或是不操作。
3、![Markdown](http://i2.muimg.com/590848/4679db649ac4c20c.png)，如这个来说，我们可以对冲上述汇率波动风险，但是昨晚罗总说套利没锁定汇率的必要，这是因为？（1）因为外汇可能需要手续费？（2）汇率的波动对冲了，套利波动更少，更难做？（3）因为如1所说，汇率影响较小，有可能存在套利赚的拟补不了外汇市场上亏的钱的情况

**Comment by gzMichael** [comment]
@XifenYE @GM163 @PwenWung 今天课程上也讨论了以上内容，所以该 Issue 内容一定会有增补，这里让 @GM163 帮忙整理 Issue 内容，讨论完成后也是收录入 Wiki 。

- 有疑问就提出，后面将会把越来越多的权限开放给你们。
- 此 Issue 同样计时 72h，之后关闭。

**Comment by XifenYE** [comment]
## 纠偏2.0
- 汇率和贴水对于套利投机者来说是敞口风险，因此在做盘面压榨套利时，要考虑升贴水和汇率带来的不利变动影响。
- 压榨利润=豆粕期价×0.79+豆油期价×0.19-大豆进口成本-120
- 反向套利：当压榨利润低于-120时，考虑进行反向套利，买DCE豆油豆粕，卖CBOT大豆。此时判断是DCE价格偏低，CBOT价格偏高。国内涨，美盘跌，则获利。
1. 汇率：假定预计人民币贬值，利多出口，利空进口，压榨利润缩减，将对DCE豆粕豆油价格形成支撑，套利风险低。如果预计人民币升值，利多榨利，不利于DCE价格上涨，套利风险提高。
2. 升贴水：近期美湾贴水报价为159，是一个偏低的报价（美湾贴水最高时达到230），预期贴水会上升，或者下降空间有限，利空榨利，将支撑DCE价格上涨，套利风险低。反之，如果预计贴水偏高，比如将降到120，套利风险提高，需要密切关注贴水变化。
- 正向套利：当压榨利润高于120时，考虑进行正向套利，卖DCE豆油豆粕，买CBOT大豆。此时判断是DCE价格偏高，CBOT价格偏低。国内跌，美盘涨，则获利。
1. 汇率：假定预计人民币贬值，DCE可能因为汇率维持高价，套利风险提高。如果预计人民币升值，将加速DCE价格下跌，套利风险降低。
2. 升贴水：预期贴水上升，或者下降空间有限，将对DCE价格形成支撑，套利风险高。反之，如果预计贴水偏高，有下降空间，则套利风险低。

**Comment by GM163** [comment]
- 贴水和汇率的变化并非影响到是否做压榨套利，而是影响到做了压榨套利以后，这两者可能的变化会给压榨套利带来何种风险，需要时刻关注其变化。
- 做反套时，贴水上升，汇率降低，都为反套的有利因素，反之
- 做正套时，贴水下降，汇率上升，都为正套的有利因素，反之 
- 关于沛文提的锁定汇率问题，我认为是做压榨套利本身就具有一定复杂性，而外汇市场又是新领域，为了套利利润，不会搞的更复杂，所以大部分都选择汇率作为敞口因素来看的。
- 问题1：风控20%，交易前有一定策略，可能自身资金与可承受损失已经等不到盈利的点。
- 问题2：例如做反套时，贴水上升，汇率也上升，如果贴水上升幅度大于汇率，风险变小，如果贴水上升幅度小于汇率，风险增大。
- 问题3：压榨利润=豆粕期价×0.79+豆油期价×0.19-大豆进口成本-120  汇率和贴水最直接影响的是到岸成本，到岸成本直接影响DCE价格，CBOT对市场反应需要时间，所以影响因素最大的是DCE价格。

**Comment by gzMichael** [comment]
这个到时了哦。
