### ISSUE TITLE
72h[TASK] 了解生猪以及禽类的消费量

### ISSUE THREAD

**Issue by gzMichael** [JianyiFutures/intern#28]
@JianyiFutures/all 

## 背景

@XifenYE 在课上提问，关于生猪价格与饲料需求的问题，引出该任务：

- 中国每年的生猪以及禽类的消费量是多少？

- 在哪里可以获取该数据？

- 从获取到的数据，是否有支持你原来的观点？原因是什么？

请根据以上线索，进行查询并提交。
标题中写了完成时限 "72h"，即 72 小时，请在相应时间内提交。根据”谁提出、谁主导、谁关闭“的原则，这个 Issue 就指派给 @XifenYE 了，请在 Issue 完结后，整理内容，然后收纳入 Wiki 。如有疑问也请提出。

**Comment by XifenYE** [comment]
# 生猪以及禽类对豆粕价格的影响
## 数据来源
- [USDA-Foreign Agricultural Service-Meat swine](https://apps.fas.usda.gov/psdonline/app/index.html#/app/advQuery?nsukey=YPmin9T1JzdLHrGGNVyhTT90hGNfRLq1DAT4xVNj7j6xL3ZgJYjtRwh4odJ%2Fl730viTpn40uv9JqrbqatMiH77PYErCggrjoYwTp1SkhDYknolPag19Ebd8%2BALfcvWj%2BS4NAjwqfqdDc%2FYL%2FqMJzKRi3K%2FNeaavj0Jiwr19Ra5N0tprVP%2BZ948FySrHrEtKD)
- [中国农业部-监测预警](http://www.moa.gov.cn/zwllm/jcyj/index.htm)
- [中国农业部-农业经济信息发布日历](http://www.moa.gov.cn/ztzl/nybrl/)
## 具体报告
### 价格 
- [生猪屠宰价格信息](http://www.moa.gov.cn/zwllm/jcyj/201704/t20170420_5576025.htm)——每月不定时公布两次
- [仔猪价格](http://www.moa.gov.cn/zwllm/jcyj/201704/t20170420_5576000.htm)——每周更新
- [畜产品和饲料集贸市场价格情况](http://www.moa.gov.cn/zwllm/jcyj/201704/t20170411_5556612.htm)——每周更新

![Markdown](http://i1.piimg.com/591986/634dc8fc6b3bcf1d.png)

### 产量&消费量
- [规模以上生猪定点屠宰企业屠宰量](http://www.moa.gov.cn/zwllm/jcyj/201703/t20170321_5532179.htm)——每月更新
-  [400个监测县生猪存栏信息](http://www.moa.gov.cn/zwllm/jcyj/201704/t20170414_5560142.htm)——每月更新

###  供需信息汇总（重点关注）
- [猪肉：农产品供需形势分析月报（大宗农产品）](http://www.moa.gov.cn/zwllm/jcyj/201704/t20170418_5572291.htm)
- [禽肉：农产品供需形势分析月报（鲜活农产品）](http://www.moa.gov.cn/zwllm/jcyj/201704/t20170418_5572293.htm)

## 影响分析
1. 一般来说，猪肉/禽肉价高，出栏量大，存栏量低，饲料需求低。相反，价格下跌，存栏量提高，饲料需求高。
2. 根据农业部发布的三月农产品供需形势分析月报，3月受供给充足、消费疲软、H7N9冲击影响，禽肉、禽蛋持续低迷。与此同时，猪肉和生猪价格均连续9周下跌，仔猪价格连续12周回升后回落。价格下跌，肉类市场供大于求，存栏量高，饲料需求高，与1-3月大豆压榨量高但豆粕库存低的情况吻合。
3. 禽类/生猪价格下行，对当前豆粕需求有利，未来需求不利，可以考虑跨期套利，比如买入M1705，卖出M1709的操作。

**Comment by XifenYE** [comment]
已收录至Wiki，Issue关闭
