### ISSUE TITLE
新人报道处

### ISSUE THREAD

**Issue by gzMichael** [JianyiFutures/intern#3]
@JianyiFutures/all 
欢迎各位新同学！在加入团队前，请先来个简短的自我介绍，让大家认识你吧。

比如像：
（以下内容仅供参考，请随意发挥）
```
 - 名字：
 - 专业：
 - 兴趣爱好：
```

**Comment by XifenYE** [comment]
### 姓名
- 叶熙芬
- Silvia
### 性别
- 妹纸
### 学校院系
- 暨南大学
- 经济学院
- 财政学
### 爱好
- 长跑（MAX: 18km）
- 健身（HIIT爱好者）
- 烹饪 （初学菜鸟）
- 吃（……）
### Wechat
- SSilviaYE

**Comment by PwenWung** [comment]
-  **名字**：王沛文（男的男的男的- -#！）
-  **专业**：国际经济与贸易 广东外语外贸大学
-  **兴趣爱好**：游泳，健身，看魔术

- 各位战友，加个好友呗[捂脸]加你们QQ没见着人 微信号wpw213112

**Comment by GM163** [comment]
姓名：弓敏
性别：女
学校：广东外语外贸大学
专业：外交学
兴趣爱好：半残国画手  半打读书爱好者

**Comment by weitouzi** [comment]
- 昵称：小微
 - 职位：期货研究小组学习委员
 - 特长：检查作业
 - 微信号：weitouzi8888
 - 听说加入【简一期货学习小组】老板会发迎新红包，不管你信不信，反正我是信了：）
 - 不知道怎么加入群吗？
 - 来，你先给我发个红包，我私信你~~~

**Comment by 65Xiaomeng65** [comment]
- 姓名：刘小萌 （Grace）
- 性别：女生
- 学校：美国理海大学
- 专业：金融分析
- 微信号：lxm8888628
- 兴趣爱好：旅行，看剧
- 因为时差原因，其实有点担心和大家交流比较少，想要和大家一起努力！

**Comment by superke7** [comment]
- **姓名:**　秦正宇
- **性别:** 　男
- **学校:** 　东北大学
- **专业:** 　金融学
- **微信:**　superke7
- 新手一枚，欢迎互相交流学习哈~
