### ISSUE TITLE
[Chaos][Discuss] 开放公共仓库，怎么玩？

### ISSUE THREAD

**Issue by gzMichael** [JianyiFutures/intern#31]
@GM163 @PwenWung @XifenYE 我把之前的 `Pull requests` 合并了，就出现一个问题：

- 大家放的目录可能不一致，怎么办？应该放哪里？
- 大家可能都往同一个目录传文件，文件名可能重复，怎么办？

这其实就是一个开放的协作环境了，我们自己制订一个规则，然后试运行吧。

本 Issue 指派给 @PwenWung 。

**Comment by PwenWung** [comment]
### 文件位置
根据目前写的文件来看，可以按以下文件夹进行分类：

 - 交易总结（Trading）：写下自己模拟盘的操作情况与感想，可以每周一贴
 - 培训与会议（Course and conference）：每周的培训总结或者会议讨论的总结
 - 期货知识（Futures basic concepts）：
可以写关于天气，养殖业，CFTC，产量及出口量的趋势，历史趋势解读，国际贸易贸易流程，贴水，汇率，正反套的理解，等等的期货相关知识
 - 报告解读(Report interpretation):对USDA或者农业部或者天气报告，基金持仓报告更新的解读
 - 读书笔记（Reading notes）：阅读了书籍或者研究报告或者看了视频，或者对期货有新的认识，可以写下所得
 
 ###  文件命名

XWDY（新建文件的日期）+主题+——名字（这个是shift+-的符号）
这样可以避免出现文件名重复的情况，以后
如：4WD6（20170422）第四次培训心得——王沛文

PS：由于文件夹只能用英文命名，加上我英文不好，大家可以说说对括号里面的英文设置还有对文件的分类，文件命名格式提出建议，以后我们统一一下。

**Comment by gzMichael** [comment]
### 为何不用中文命名
关于中文命名，在页面上上感受不到的，但如果在命令行，会看得很清楚，这个 @XifenYE 会有感受。

比如 Wiki 中关于命名的就有这么几条：
- 永远不用中文名来作任何命名
- 永远不用拼音来作任何命名
- 永远使用 UTF-8 编码

下面我举个例子说明一下：
根目录 `0WD4问题回答.md` 这个文件， 有含中文字符，在命令行看到的是其 `UTF-8` 编码，实际效果如下：

> 0WD4\351\227\256\351\242\230\345\233\236\347\255\224.md

在命令行非常难进行输入，并且无法判断该文件是哪个文件。所以命名时，还是要用英文，但具体怎么命名，你们可以继续讨论。

### 参考
[Wiki 禁止事项清单](https://github.com/JianyiFutures/intern/wiki/HbNotDoIt)
[缩写规约](https://github.com/JianyiFutures/intern/wiki/HbShortRule)

**Comment by gzMichael** [comment]
这样吧，我给个建议：
- 新开 [_draft](https://github.com/JianyiFutures/intern/tree/master/_draft) 仓库目录
- 文件名为 `[总周数]_[github id]_[内容简述 英文,小写单词,用-连接].md`
如：3w_gzmichael_cards-1.md

只是建议，大家有什么想法就提，这些都是靠玩出来的，可不是作业。

**Comment by GM163** [comment]
可以再规定一些缩写吧 

常用的有每周例行作业可以用hm，例行笔记可以用note，如3WD2_GM163_hm，这是具体命名，目录的话可以分大目录HM，里面又有小目录3WHM,小目录下面写具体文件。

每周的问题汇总可以用ask（我觉得没必要每个问题汇总都在wiki开一个page，就每周问题汇总一下，3Wask）

**Comment by gzMichael** [comment]
@GM163 可以，支持。定下来就开始按制订的规则玩吧。

**Comment by PwenWung** [comment]
@GM163 如果按每周汇总问题转到wiki的话，时间一长，可能不便于以后查找，如果按类别进行汇总会不会好一点，比如按汇率，贴水，产量，面积……的相关性强弱进行问题的汇总

**Comment by GM163** [comment]
那有两面都涉及的怎么归类呢，我觉得wiki不可能只整理一次，月啊年度还要整理，我觉得按时间排比较科学，你觉得呢  @PwenWung

**Comment by PwenWung** [comment]
两面都相关的话，到时候想查某个问题的时候，A找不到的话就自然会去B找了，应该查找方面不是问题。而WIKI的作用感觉是为了方便以后查到、修改和更新相关问题吧

**Comment by gzMichael** [comment]
这个有形成共识吗？

**Comment by PwenWung** [comment]
经过讨论，得到共同结果：
1. 私人库任务作业，按"[5W3D(20170426)]+主题"进行命名
2. 私人库按自己的个人习惯摆放目录，但若出现需要集体完成的某一文档，我们需要提前统一文件目录和文件命名
3. WiKi：pages命名 按"5W Ask1"进行，每个月月底整理一次Pages至导航栏
4. 导航栏按主题内容进行分类：基本知识，供给因素，需求因素，其他因素

**Comment by PwenWung** [comment]
讨论结束，转到[WiKi](https://github.com/JianyiFutures/intern/wiki/5W-Task1)保存，之后会对规约进行更替
