### ISSUE TITLE
[LOG] 更新 Wiki 4w 作业汇总

### ISSUE THREAD

**Issue by gzMichael** [JianyiFutures/intern#34]
@PwenWung @GM163 @XifenYE 我觉得这样才是汇总吧：
https://github.com/JianyiFutures/intern/wiki/Hw4w

- 增加文内导航
- 增加文内锚点，可互相跳转

**Comment by XifenYE** [comment]
确实好很多，以后就按这样整理吧~~还有就是汇总作业、提问、任务pages的命名没有固定有点混乱，是不是有必要固定下来，看起来也比较有条理，比如
作业：Hw4w
问题：Ask4w
任务：Task4w
比较简单
大家的意见呢
