### ISSUE TITLE
[Chaos][Discuss] Wiki Pages 命名讨论

### ISSUE THREAD

**Issue by gzMichael** [JianyiFutures/intern#36]
#34 中提到讨论 Wiki Pages 的命名，为此开 Issue 讨论
@XifenYE 的建议是：
- 作业：Hw4w
- 问题：Ask4w
- 任务：Task4w

**Comment by GM163** [comment]
同意，每周汇总然后各类开一个page

**Comment by XifenYE** [comment]
已解决，issue关闭
