### ISSUE TITLE
大家不用提交Pull requests，发链接即可

### ISSUE THREAD

**Issue by gzMichael** [JianyiFutures/intern#6]
@JianyiFutures/all @GM163 可以在自己的目录写好文件后，在这里提交。像下面这样：
[我的仓库链接](https://github.com/GM163/intern/blob/master/test.md)

**Comment by gzMichael** [comment]
@XifenYE 同学已经摸索了Github/Markdown，也写下了自己对期货的初步了解，速度很快啊！赞一个！
必须贴出来给大家看一下：
[Foundation/note/我眼中的期货.md](https://github.com/XifenYE/intern/blob/master/Foundation/note/%E6%88%91%E7%9C%BC%E4%B8%AD%E7%9A%84%E6%9C%9F%E8%B4%A7.md)
[Tools/Note/Github初体验.md](https://github.com/XifenYE/intern/blob/master/Tools/Notes/Github%E5%88%9D%E4%BD%93%E9%AA%8C.md)
[Tools/Note/关于Markdown.md](https://github.com/XifenYE/intern/blob/master/Tools/Notes/%E5%85%B3%E4%BA%8EMarkdown.md)

**Comment by PwenWung** [comment]
[我的仓库链接](https://github.com/PwenWung/intern)
