### ISSUE TITLE
“期货初接触”作业提交处

### ISSUE THREAD

**Issue by gzMichael** [JianyiFutures/intern#9]
今天初步介绍了期货的基本知识，以及豆粕这个期货品种的初步认识，大家听了之后有什么收获呢？

请大家于 **0wd5(170324)** 前在下面回复提交。

下面的问题只为引起大家的思考，不一定需要逐个回答（有兴趣回答的除外）。

- 什么是主力合约？

- 商品的供需是由什么决定的？如果我自己尝试去做供求分析的话，会从哪些方面入手，将怎样做？

- 豆粕是一个怎样的商品？从哪里可以获取到关于它的更多信息？

- 今天的课程多次提到了USDA的报告，我可以在哪里获取到这些报告呢？

## 关于作业的提交格式

建议大家用下面的方式进行回复：

我的笔记位置：[总结文件1](#),  [总结文件2](#)

**Comment by gzMichael** [comment]
忘记 @JianyiFutures/all 了

**Comment by PwenWung** [comment]
笔记位置：[从基本面分析商品期货价格的因素](https://github.com/PwenWung/intern/blob/master/PAPER/%E4%BB%8E%E5%9F%BA%E6%9C%AC%E9%9D%A2%E5%88%86%E6%9E%90%E5%95%86%E5%93%81%E6%9C%9F%E8%B4%A7%E4%BB%B7%E6%A0%BC%E7%9A%84%E5%9B%A0%E7%B4%A0.md)    [为什么选择研究豆粕](https://github.com/PwenWung/intern/blob/master/PAPER/%E4%B8%BA%E4%BB%80%E4%B9%88%E9%80%89%E6%8B%A9%E7%A0%94%E7%A9%B6%E8%B1%86%E7%B2%95.md)     [为什么选择主力合约](https://github.com/PwenWung/intern/blob/master/PAPER/%E4%B8%BA%E4%BB%80%E4%B9%88%E9%80%89%E6%8B%A9%E4%B8%BB%E5%8A%9B%E5%90%88%E7%BA%A6.md)

**Comment by XifenYE** [comment]
笔记位置：
[3.20见面会心得](https://github.com/XifenYE/intern/blob/master/Foundation/note/3.20%E8%A7%81%E9%9D%A2%E4%BC%9A%E5%BF%83%E5%BE%97.md)
[基础知识整理](https://github.com/XifenYE/intern/blob/master/USDA_Reports/Notes/%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86%E6%95%B4%E7%90%86.md)
[大豆、豆粕价格分析](https://github.com/XifenYE/intern/blob/master/USDA_Reports/%E7%AC%94%E8%AE%B0/%E5%A4%A7%E8%B1%86%E3%80%81%E8%B1%86%E7%B2%95%E4%BB%B7%E6%A0%BC%E5%88%86%E6%9E%90.md)
[3.23交易心得](https://github.com/XifenYE/intern/blob/master/Trading/note/3.23%E4%BA%A4%E6%98%93%E5%BF%83%E5%BE%97.md)

**Comment by gzMichael** [comment]
作业点评：

@PwenWung：
[点评1](https://github.com/PwenWung/intern/commit/ce8d800a761c8029d7db1df17c7d2f31c4eb8a62)
[点评2](https://github.com/PwenWung/intern/commit/fabf17b1e27cde0dd37aca01995ccc9175a568eb)

@XifenYE ：
[点评1](https://github.com/XifenYE/intern/commit/11b3114f27121b2d5ab91046a677d39e4a3e79b4)
[点评2](https://github.com/XifenYE/intern/commit/eaf31616b0888bde42cb3e5c9481e6571cac6c85)
[点评3](https://github.com/XifenYE/intern/commit/3129ec9b75a08e6bfcad7bb2c6cb832ce715492a)

同学们的作业完成得不错，继续加油！ :+1:

**Comment by gzMichael** [comment]
本次作业提交已完成，大家如果有更新补充的，Close之后还可以在后面更新。

**Comment by GM163** [comment]
https://github.com/GM163/intern/blob/master/0W1%20周一会议心得.md

**Comment by GM163** [comment]
笔记位置：
[会议总结](https://github.com/GM163/intern/blob/master/0W1%20%E5%91%A8%E4%B8%80%E4%BC%9A%E8%AE%AE%E5%BF%83%E5%BE%97.md)

[基础知识](https://github.com/GM163/intern/blob/master/0WD3%E5%9F%BA%E6%9C%AC%E7%9F%A5%E8%AF%86.md)

[问题回答](https://github.com/GM163/intern/blob/master/0WD4%E9%97%AE%E9%A2%98%E5%9B%9E%E7%AD%94.md)

**Comment by qinzhengyu** [comment]
我的笔记位置:[期货初接触](https://github.com/qinzhengyu/intern/blob/master/Foundation/note/%E6%9C%9F%E8%B4%A7%E5%88%9D%E6%8E%A5%E8%A7%A6.md)

**Comment by superke7** [comment]
笔记位置：　　
[期货初体验](https://github.com/qinzhengyu/intern/blob/master/Foundation/note/%E6%9C%9F%E8%B4%A7%E5%88%9D%E6%8E%A5%E8%A7%A6.md)　　
[商品期货交易问与答](https://github.com/qinzhengyu/intern/blob/master/Trading/%E5%95%86%E5%93%81%E6%9C%9F%E8%B4%A7%E4%BA%A4%E6%98%93%E5%AD%A6%E4%B9%A0%E9%97%AE%E4%B8%8E%E7%AD%94.md)

**Comment by superke7** [comment]
笔记位置:  
[期货相关问题及报告获取](https://github.com/qinzhengyu/intern/blob/master/USDA_Reports/%E5%A4%A7%E8%B1%86%E6%9C%9F%E8%B4%A7%E5%88%9D%E6%8E%A2%E8%AE%A8-1.md)
